services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://omwoyojohn:omwoyojohn@cluster0.acjt20i.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - yolo-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - yolo-net

networks:
  yolo-net:
    driver: bridge
